[package]
name = "toy-runtime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deno_core = "0.148.0"
tokio = { version = "1.20.1", features = ["full"] }
